version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./database/:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: dGTAg697ryvb4hB
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 2L9kPw3sngUJZMgU

   wordpress:
     depends_on:
       - db
     image: wordpress:latest     
     ports:
       - "80:80"
       - "443:443"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: 2L9kPw3sngUJZMgU       
     volumes: 
       - ./wp-content:/var/www/html/wp-content # whole directory mapping
      #  - ./wp-content/themes/shopkeeper:/var/www/html/wp-content/themes/shopkeeper # mapping our custom theme to the container
      #  - ./wp-content/plugins:/var/www/html/wp-content/plugins # map our plugins to the container
      #  - ./wp-content/uploads:/var/www/html/wp-content/uploads # map our uploads to the container     
